### ISSUE TITLE
importlab crashes on file with tensorflow import

### ISSUE THREAD

**Issue by uriva** [google/importlab#19]
importlab version: 0.3.0

When running `importlab my_file.py --tree` on a file with contents `import tensorflow`, the result is the following exception:
```
Reading 1 files
/home/me/.local/lib/python3.6/site-packages/IPython/kernel/__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated since IPython 4.0.You should import from ipykernel or jupyter_client instead.
  "You should import from ipykernel or jupyter_client instead.", ShimWarning)
Traceback (most recent call last):
  File "/usr/local/bin/importlab", line 79, in <module>
    sys.exit(main())
  File "/usr/local/bin/importlab", line 63, in main
    import_graph = graph.ImportGraph.create(env, args.inputs)
  File "/usr/local/lib/python3.6/dist-packages/importlab/graph.py", line 258, in create
    import_graph.add_file_recursive(os.path.abspath(filename))
  File "/usr/local/lib/python3.6/dist-packages/importlab/graph.py", line 128, in add_file_recursive
    deps, broken = self.get_file_deps(filename)
  File "/usr/local/lib/python3.6/dist-packages/importlab/graph.py", line 272, in get_file_deps
    for imp in parsepy.get_imports(filename, self.env.python_version):
  File "/usr/local/lib/python3.6/dist-packages/importlab/parsepy.py", line 79, in get_imports
    imports = import_finder.get_imports(filename)
  File "/usr/local/lib/python3.6/dist-packages/importlab/import_finder.py", line 136, in get_imports
    imports.append(i + (resolve_import(name, is_from, is_star),))
  File "/usr/local/lib/python3.6/dist-packages/importlab/import_finder.py", line 116, in resolve_import
    ret = _resolve_import(name)
  File "/usr/local/lib/python3.6/dist-packages/importlab/import_finder.py", line 98, in _resolve_import
    return _resolve_import_3(name)
  File "/usr/local/lib/python3.6/dist-packages/importlab/import_finder.py", line 80, in _resolve_import_3
    spec = importlib.util.find_spec(name)  # pytype: disable=module-attr
  File "/usr/lib/python3.6/importlib/util.py", line 88, in find_spec
    parent = __import__(parent_name, fromlist=['__path__'])
  File "/home/me/.local/lib/python3.6/site-packages/IPython/utils/_process_win32.py", line 23, in <module>
    from ctypes.wintypes import LPCWSTR, HLOCAL
  File "/usr/lib/python3.6/ctypes/wintypes.py", line 20, in <module>
    class VARIANT_BOOL(ctypes._SimpleCData):
ValueError: _type_ 'v' not supported

```

**Comment by martindemello** [comment]
i tried to reproduce this via:

1. install python 3.6.6. (via pyenv)
2. create a virtualenv
3. pip install tensorflow
4. pip install importlab
5. importlab --tree my_file.py

and it worked fine. could you describe your setup?

**Comment by martindemello** [comment]
looking at your backtrace, this might be a windows-specific issue, since the crash occurred while `importlib` was processing `ctypes.wintypes`. i'll investigate further.

**Comment by martindemello** [comment]
okay, can reproduce the error message by `import ctypes.wintypes` under linux. i'm not sure why it was trying to do that; since i cannot reproduce it locally i'll try pushing a new version of importlab with detailed debug logging.

**Comment by uriva** [comment]
I can confirm that when using virtualenv this error doesn't trigger.

**Comment by martindemello** [comment]
i can no longer reproduce this even by import cytypes.wintypes, so i think some of the fixes around gracefully handling unreadable files addressed this issue as well. please reopen the bug if it is still happening for you.
